// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { ListView, Palette } from "std-widgets.slint";
import { EditorFontSettings, EditorSpaceSettings, SelectionPalette } from "./styling.slint";
import { Api, SelectionStackFrame } from "../api.slint";

component PopupInner {
    in property <length> max-popup-height: 600px;

    in property <length> selection-x: 0px;
    in property <length> selection-y: 0px;
    in property <[SelectionStackFrame]> selection-stack: [
        {
            width: 100%,
            height: 100%,
            x: 0%,
            y: 0%,
            embedding-level: 0,
            is-layout: false,
            is-interactive: true,
            is-selected: false,
            type-name: "TypeA",
            id: "some_a",
        },
        {
            width: 50%,
            height: 50%,
            x: 0%,
            y: 0%,
            embedding-level: 0,
            is-layout: true,
            is-interactive: false,
            is-selected: true,
            type-name: "TypeB",
            id: "some_b",
        },
        {
            width: 50%,
            height: 50%,
            x: 50%,
            y: 50%,
            embedding-level: 2,
            is-layout: false,
            is-interactive: true,
            is-selected: false,
            type-name: "TypeA",
            id: "some_a",
        },
        {
            width: 50%,
            height: 50%,
            x: 0%,
            y: 50%,
            embedding-level: 1,
            is-layout: true,
            is-interactive: false,
            is-selected: false,
            type-name: "TypeB",
            id: "some_b",
        },
        {
            width: 50%,
            height: 50%,
            x: 25%,
            y: 25%,
            embedding-level: 0,
            is-layout: false,
            is-interactive: false,
            is-selected: false,
            type-name: "TypeB",
            id: "some_b",
        }
    ];
    
    private property <length> measured-rect-size: 50px;
    private property <length> frame-height: self.measured-rect-size + EditorSpaceSettings.default-padding * 2;

    private property <int> max-visible-frames: Math.floor((root.max-popup-height / 1px) / (self.frame-height / 1px));
    private property <int> visible-frames: Math.min(self.max-visible-frames, root.selection-stack.length);

    width: 250px;
    height: visible-frames * frame-height;

    function select-frame(index: int) {
        if index >= 0 {
            list-view.viewport-y = (index - (self.visible-frames / 2)) * self.frame-height;
        } else {
            list-view.viewport-x = 0px;
        }
    }

    list-view := ListView {
        for frame[index] in root.selection-stack: frame-rect := Rectangle {
            width: 100%;
            height: root.frame-height;

            background: frame.is-selected ? Palette.alternate-background : Palette.background;

            if frame.is-selected: Rectangle {
                init() => {
                    root.select-frame(index);
                }
            }

            function frame-color(frame: SelectionStackFrame) -> brush {
                if frame.is-interactive {
                    return SelectionPalette.interactive-element-selection-secondary;
                } else if frame.is-layout {
                    return SelectionPalette.layout-element-selection-secondary;
                } else {
                    return SelectionPalette.general-element-selection-secondary;
                }
            }
            function frame-background(frame: SelectionStackFrame) -> brush {
                if frame.is-interactive {
                    return SelectionPalette.interactive-element-selection-primary;
                } else if frame.is-layout {
                    return SelectionPalette.layout-element-selection-primary;
                } else {
                    return SelectionPalette.general-element-selection-primary;
                }
            }

            function calculate_pos(p: length, percent: float) -> length {
                return Math.round((measure-rect.width / 1px) * percent) * 1px;
            }
            function calculate_size(p: length, percent: float) -> length {
                return Math.max(Math.round((p / 1px) * percent), 2) * 1px;
            }

            HorizontalLayout {
                padding: EditorSpaceSettings.default-padding / 2.0;
                spacing: EditorSpaceSettings.default-spacing;

                Rectangle {
                    width: EditorSpaceSettings.group-indent * frame.embedding-level;
                    height: 100%;
                }

                Rectangle {
                    clip: true;
                    width: root.measured-rect-size + EditorSpaceSettings.default-padding;
                    height: root.measured-rect-size + EditorSpaceSettings.default-padding;

                    measure-rect := Rectangle {
                        width: root.measured-rect-size;
                        height: root.measured-rect-size;

                        border-color: black;
                        border-width: 1px;
                        placeholder-rect := Rectangle {
                            x: calculate_pos(measure-rect.width, frame.x);
                            y: calculate_pos(measure-rect.height, frame.y);
                            width: calculate_size(measure-rect.width, frame.width);
                            height: calculate_size(measure-rect.height, frame.height);

                            border-color: frame-rect.frame-color(frame);
                            border-width: 1px;
                            background: frame-rect.frame-background(frame);
                        }
                    }
                }

                VerticalLayout {
                    padding: EditorSpaceSettings.default-padding / 2.0;
                    spacing: EditorSpaceSettings.default-spacing;

                    Text {
                        text: frame.type-name;
                    }

                    Text {
                        text: frame.id;
                        font-weight: EditorFontSettings.bold-font-weight;
                    }
                }
            }
        }
    }
}

export component SelectionPopup {
    public function show-selection-stack(x: length, y: length) {
        debug("show-selection-stack called");
        self.selection-x = x;
        self.selection-y = y;
        self.selection-stack = Api.selection-stack-at(self.selection-x, self.selection-y);

        popup.show();
    }

    public function close-selection-stack() {
        self.selection-x = 0;
        self.selection-y = 0;
        self.selection-stack = [];

        popup.close();
    }

    public function select-behind() {
        if self.selection-stack.length > 0 {
            Api.select-behind(self.selection-x, self.selection-y, true, false);
            self.selection-stack = Api.selection-stack-at(self.selection-x, self.selection-y);
        }
    }

    public function select-before() {
        if self.selection-stack.length > 0 {
            Api.select-behind(self.selection-x,self.selection-y, true, true);
            self.selection-stack = Api.selection-stack-at(self.selection-x, self.selection-y);
        }
    }

    in property <length> max-popup-height;

    private property <[SelectionStackFrame]> selection-stack;
    private property <length> selection-x;
    private property <length> selection-y;

    popup := PopupWindow {
        x: 20px;
        y: 20px;

        width <=> inner.width;
        height <=> inner.height;

        init() => {
            debug("PopupWindow initialized: ", self.width, "x", self.height);
        }

        in property <length> max-popup-height: root.max-popup-height;
        in property <[SelectionStackFrame]> selection-stack: root.selection-stack;
        in property <length> selection-x: root.selection-x;
        in property <length> selection-y: root.selection-y;

        inner := PopupInner {
            max-popup-height <=> popup.max-popup-height;
            selection-stack <=> popup.selection-stack;
            selection-x <=> popup.selection-x;
            selection-y <=> popup.selection-y;
        }
    }
}
