// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { ListView, Palette } from "std-widgets.slint";
import { EditorFontSettings, EditorSpaceSettings, SelectionPalette } from "./styling.slint";
import { Api, SelectionStackFrame } from "../api.slint";

component PopupInner inherits Rectangle {
    in property <length> max-popup-height: 600px;
    property <percent> window-height: 100%;
    property <percent> window-width: 100%;
    in property <length> selection-x: 0px;
    in property <length> selection-y: 0px;
    in property <[SelectionStackFrame]> selection-stack: [
        {
            width: 100%,
            height: 40%,
            x: 10%,
            y: 0%,
            embedding-level: 0,
            is-layout: false,
            is-interactive: true,
            is-selected: false,
            type-name: "TypeA",
            id: "some_a",
        },
        {
            width: 50%,
            height: 50%,
            x: 0%,
            y: 0%,
            embedding-level: 0,
            is-layout: true,
            is-interactive: false,
            is-selected: true,
            type-name: "TypeB",
        },
        {
            width: 50%,
            height: 50%,
            x: 50%,
            y: 50%,
            embedding-level: 2,
            is-layout: false,
            is-interactive: true,
            is-selected: false,
            type-name: "TypeA",
            id: "some_a",
        },
        {
            width: 250%,
            height: 50%,
            x: 50%,
            y: 50%,
            embedding-level: 2,
            is-layout: false,
            is-interactive: false,
            is-selected: false,
            type-name: "Rectangle",
            id: "alsoInteractive",
        },
        {
            width: 50%,
            height: 50%,
            x: 0%,
            y: 50%,
            embedding-level: 1,
            is-layout: true,
            is-interactive: false,
            is-selected: false,
            type-name: "VerticalLayout",
        },
        {
            width: 10%,
            height: 5%,
            x: 25%,
            y: 25%,
            embedding-level: 0,
            is-layout: false,
            is-interactive: false,
            is-selected: false,
            type-name: "Text",
        },
        {
            width: 50%,
            height: 100%,
            x: 0%,
            y: 0%,
            embedding-level: 0,
            is-layout: false,
            is-interactive: false,
            is-selected: false,
            type-name: "Window",
            id: "",
        }
    ];
    private property <length> max-rect-size: 40px;
    private property <length> frame-height: self.max-rect-size + EditorSpaceSettings.default-padding * 2;

    private property <int> max-visible-frames: Math.floor((root.max-popup-height / 1px) / (self.frame-height / 1px));
    private property <int> visible-frames: Math.min(self.max-visible-frames, root.selection-stack.length);
    border-radius: 5px;
    border-width: 0.5px;
    background: Palette.background;
    drop-shadow-blur: 10px;
    drop-shadow-color: black;
    border-color: lightgray;

    width: 250px;
    height: visible-frames * frame-height;

    function select-frame(index: int) {
        if index >= 0 {
            list-view.viewport-y = (index - (self.visible-frames / 2)) * self.frame-height;
        } else {
            list-view.viewport-x = 0px;
        }
    }
    for frame[index] in root.selection-stack: find-window := Rectangle {
        init() => {
            if frame.type-name == "Window" {
                root.window-height = frame.height;
                root.window-width = frame.width;
                debug(root.window-height);
                // debug("Window size: " + root.window-width + " by " + root.window-height);
            }
        }
    }

    list-view := ListView {
        for frame[index] in root.selection-stack: frame-rect := Rectangle {
            width: 100%;
            height: root.frame-height;
            background: frame.is-selected ? Palette.alternate-background : transparent;
            Rectangle {
                height: 1px;
                background: Palette.foreground.transparentize(0.9);
                y: 0;
            }

            if frame.is-selected: Rectangle {
                y: 0;

                background: Palette.accent-background;
                init() => {
                    root.select-frame(index);
                }
            }

            function frame-color(frame: SelectionStackFrame) -> brush {
                return SelectionPalette.interactive-element-selection-secondary;

                if frame.is-interactive {
                    return SelectionPalette.interactive-element-selection-secondary;
                } else if frame.is-layout {
                    return SelectionPalette.layout-element-selection-secondary;
                } else {
                    return SelectionPalette.general-element-selection-secondary;
                }
            }
            function frame-background(frame: SelectionStackFrame) -> brush {
                if frame.is-interactive {
                    return Palette.accent-background.transparentize(0.8); //SelectionPalette.interactive-element-selection-primary;
                } else if frame.is-layout {
                    return transparent; //SelectionPalette.layout-element-selection-primary;
                } else {
                    return Colors.gray;
                    //this could be frame.color - for any shape whatever is most visible;
                }
            }

            function calculate_pos(p: length, percent: float) -> length {
                return Math.round((measure-rect.width / 1px) * percent) * 1px;
            }
            function calculate_size(p: length, percent: float) -> length {
                return Math.max(Math.round((p / 1px) * percent), 2) * 1px;
            }

            HorizontalLayout {
                visible: (frame.type-name == "Window") ? false : true;
                padding-left: EditorSpaceSettings.default-padding / 2.0;
                spacing: EditorSpaceSettings.default-spacing / 2.0;

                Rectangle {
                    width: EditorSpaceSettings.group-indent * frame.embedding-level;
                    height: 100%;
                    background: Palette.alternate-background;
                    Rectangle {
                        x: parent.width;
                        width: 1px;
                        height: 100%;
                        // background: Palette.foreground;
                    }
                }
/*
            width: root.window-height > root.window-width ? 100% : root.window-width;
            height: root.window-height <= root.window-width ? 100% : root.window-height;
*/
                Rectangle {
                    clip: true;
                    y: EditorSpaceSettings.default-padding/2;
                    width: root.max-rect-size + EditorSpaceSettings.default-padding;
                    height: root.max-rect-size + EditorSpaceSettings.default-padding;
                    measure-rect := Rectangle {
                        width: root.window-width * root.max-rect-size;
                        height: root.window-height * root.max-rect-size;

                        border-color: frame.is-selected ? Palette.accent-foreground.transparentize(0.6) : Palette.foreground.transparentize(0.85);
                        border-width: 1px;
                        placeholder-rect := Rectangle {
                            x: calculate_pos(measure-rect.width, frame.x);
                            y: calculate_pos(measure-rect.height, frame.y);
                            width: calculate_size(measure-rect.width, frame.width);
                            height: calculate_size(measure-rect.height, frame.height);

                            border-color: frame-rect.frame-color(frame);
                            border-width: 0.5px;
                            background: frame-rect.frame-background(frame);
                            if frame.is-layout: Rectangle {
                                border-color: Palette.foreground;
                                border-width: 0.5px;
                                Rectangle {
                                    background: Palette.foreground;
                                    height: 0.5px;
                                }

                                Rectangle {
                                    background: Palette.foreground;
                                    width: 0.5px;
                                }
                            }
                            if frame.is-interactive: Rectangle {
                                border-color: Palette.foreground;
                                border-width: 0.5px;
                                clip: true;
                            }
                        }
                    }
                }

                VerticalLayout {
                    padding-top: EditorSpaceSettings.default-padding;
                    padding-left: EditorSpaceSettings.default-padding;
                    spacing: EditorSpaceSettings.default-spacing;
                    alignment: center;

                    if frame.id != "": Text {
                        text: frame.id;
                        color: frame.is-selected ? Palette.accent-foreground : Palette.foreground;
                        font-weight: EditorFontSettings.bold-font-weight;
                        font-size: EditorFontSettings.label.font-size;
                    }

                    Text {
                        text: frame.type-name + (frame.is-interactive ? " (TouchArea)" : "");
                        color: frame.is-selected ? Palette.accent-foreground : Palette.foreground;
                        font-size: EditorFontSettings.label-sub.font-size;
                        font-italic: true;
                    }
                }
            }
        }
    }
}

export component SelectionPopup {
    public function show-selection-stack(x: length, y: length) {
        debug("show-selection-stack called");
        self.selection-x = x;
        self.selection-y = y;
        self.selection-stack = Api.selection-stack-at(self.selection-x, self.selection-y);

        popup.show();
    }

    public function close-selection-stack() {
        self.selection-x = 0;
        self.selection-y = 0;
        self.selection-stack = [];

        popup.close();
    }

    public function select-behind() {
        if self.selection-stack.length > 0 {
            Api.select-behind(self.selection-x, self.selection-y, true, false);
            self.selection-stack = Api.selection-stack-at(self.selection-x, self.selection-y);
        }
    }

    public function select-before() {
        if self.selection-stack.length > 0 {
            Api.select-behind(self.selection-x,self.selection-y, true, true);
            self.selection-stack = Api.selection-stack-at(self.selection-x, self.selection-y);
        }
    }

    in property <length> max-popup-height;

    private property <[SelectionStackFrame]> selection-stack;
    private property <length> selection-x;
    private property <length> selection-y;

    popup := PopupWindow {
        x: 20px;
        y: 20px;

        init() => {
            debug("PopupWindow initialized");
        }

        in property <length> max-popup-height: root.max-popup-height;
        in property <[SelectionStackFrame]> selection-stack: root.selection-stack;
        in property <length> selection-x: root.selection-x;
        in property <length> selection-y: root.selection-y;

        VerticalLayout {
            inner := PopupInner {
                max-popup-height <=> popup.max-popup-height;
                selection-stack <=> popup.selection-stack;
                selection-x <=> popup.selection-x;
                selection-y <=> popup.selection-y;
            }
        }
    }
}
