import { Button, Palette, StandardButton, ScrollView } from "std-widgets.slint";
import { EditorSpaceSettings } from "../components/styling.slint";
import { Spreadsheet } from "../components/spreadsheet.slint";
import { Api, PreviewData, PropertyValueTable } from "../api.slint";

import { WindowGlobal } from "../windowglobal.slint";
import { EditorSizeSettings } from "styling.slint";

component SpreadsheetPopup inherits PopupWindow {
    in property <string> property-group-id;
    in property <PreviewData> preview-data;
    in property <PropertyValueTable> current-table;

    close-policy: close-on-click-outside;

    Rectangle {
        background: Palette.accent-background;
        
        VerticalLayout {
            Dialog {
                property <length> dialog-width;
                property <length> dialog-height;
    
                title: root.preview-data.has-setter ? "Edit Values" : "View Values"; 

                VerticalLayout {
                    padding-top: EditorSpaceSettings.default-padding;
                    spacing: EditorSpaceSettings.default-spacing;
                    Text {
                        text: spread-sheet.preview-data.name;
                        horizontal-alignment: center;
                        font-weight: 800;
                    }
                    ScrollView {
                        spread-sheet := Spreadsheet {
                            property-group-id <=> root.property-group-id;
                            preview-data <=> root.preview-data;
                            current-table <=> root.current-table;
                        }
                    }
                }

                StandardButton {
                    kind: StandardButtonKind.ok;
                    clicked => {
                        // TODO: Apply changes!
                        root.close();
                    }
                }
                StandardButton {
                    kind: StandardButtonKind.cancel;
                    clicked => { root.close(); }
                }
            }
        }
        }
}

export component SpreadsheetDialog {
    private property <string> property-group-id;
    private property <PreviewData> preview-data;
    private property <PropertyValueTable> current-table;

    public function edit-in-spreadsheet(property-group-id: string, data: PreviewData) {
        root.property-group-id = property-group-id;
        root.preview-data = data;
        root.current-table = Api.get-property-value-table(property-group-id, data.name);

        spreadsheet.show();
    }

    spreadsheet := SpreadsheetPopup {
        property-group-id <=> root.property-group-id;
        preview-data <=> root.preview-data;
        current-table <=> root.current-table;
    }
}
