// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { LineEdit, Palette, VerticalBox, CheckBox, ComboBox, ScrollView, Button, HorizontalBox, SpinBox, Slider } from "std-widgets.slint";

import { Api, ElementInformation, PropertyDeclaration, PropertyGroup, PropertyInformation, PropertyValue, PropertyValueKind } from "../api.slint";
import { GroupHeader } from "../components/group.slint";
import { BodyStrongText } from "../components/body-strong-text.slint";
import { BodyText } from "../components/body-text.slint";
import { StateLayer } from "../components/state-layer.slint";
import { EditorSizeSettings, Icons, EditorAnimationSettings, EditorSpaceSettings, EditorSizeSettings, EditorFontSettings } from "../components/styling.slint";

export global style {
    out property <length> grid-margin:5px;
    out property <length> min-distance:5px;
}

component CodeButton inherits Button {
    in property <ElementInformation> element-information;
    in property <PropertyInformation> property-information;

    text: @tr("Code");
    clicked => {
        Api.show-document-offset-range(
            element-information.source-uri,
            Api.property-declaration-ranges(property-information.name).defined-at.expression-range.start,
            Api.property-declaration-ranges(property-information.name).defined-at.expression-range.start,
            true,
        );
    }
}

component ResetButton inherits Button {
    in property <ElementInformation> element-information;
    in property <PropertyInformation> property-information;

    text: @tr("Reset");
    clicked => {
        Api.set-code-binding(
            element-information.source-uri,
            element-information.source-version,
            element-information.range.start,
            property-information.name,
            "",
        );
    }
}

component LengthProperty {
    in property <ElementInformation> element-information;
    in property <PropertyInformation> property-information;
    in property <string> property-name;
    HorizontalLayout {
        spacing: EditorSpaceSettings.default-spacing;
        BodyText {
            text: property-name;
            horizontal-stretch: 0;
        }

        Rectangle {
            width: EditorSpaceSettings.default-padding;
            horizontal-stretch: 1;
        }

        // alignment: stretch;
        LineEdit {
            text: "15";
            width: 80px;
            horizontal-stretch: 0;
        }

        ComboBox {
            model: [
                "px",
                "pt",
                "in",
                "mm",
                "cm",
            ];
            width: 80px;
            horizontal-stretch: 0;
        }
    }
}

component ColourWidget inherits Rectangle {
    property <int> gVal:30;
    z: 1;
    width: 100%;
    background: Palette.alternate-background;
    VerticalLayout {
        padding: 5px;
        spacing: -10pt;
        HorizontalBox {

            // alignment: stretch;
            Rectangle {
                background: red;
                width: 30px;
            }

            hex := LineEdit {
                text: "#ff0000";
                horizontal-stretch: 0;
                width: 80px;
            }
        }

        HorizontalBox {
            ComboBox {
                model: ["RGB", "RGBA", "HSL", "Palettes"];
                // width: 80px;
                horizontal-stretch: 0;
                width: 100%;
            }
        }

        HorizontalBox {

            // alignment: stretch;
            Text {
                text: "r:";
                width: 20px;
                vertical-alignment: center;
            }

            Slider {
                visible: (parent.width > 200px);
                value: 255;
            }

            SpinBox {
                // horizontal-stretch: 1;
                width: 100%;
                value: 255;
                maximum: 255;
            }
        }

        HorizontalBox {

            // alignment: stretch;
            Text {
                text: "g:";
                width: 20px;
                horizontal-stretch: 1;
                vertical-alignment: center;
            }

            Rectangle {
                visible: (root.width > 200px);
                Slider {
                    z: 1;
                    x: 0;
                    value: gVal;
                }

                Rectangle {
                    width: gVal * 1px;
                    height: 3px;
                    background: green;
                    x: 0;
                    y: 0;
                }
            }

            SpinBox {
                // horizontal-stretch: 1;
                width: 100%;
                value: gVal;
                maximum: 255;
            }
        }

        HorizontalBox {

            // alignment: stretch;
            Text {
                text: "b:";
                width: 20px;
                horizontal-stretch: 1;
                vertical-alignment: center;
            }

            Slider {
                visible: (parent.width > 200px);
                value: 0;
            }

            SpinBox {
                // horizontal-stretch: 1;
                width: 100%;
                value: 0;
                maximum: 255;
            }
        }
    }
}

export component ExpandableProperty inherits Rectangle {
    callback toggled;
    in-out property <bool> checked:true;
    property <duration> dur:300ms;
    in-out property <color> headerBG: Palette.alternate-background;
    in-out property <bool> enabled:true;
    in property <string> title: "Title";
    clip:true;
    width: 100%;
    z:1;
    height: header.height +10px + (root.checked ? content.preferred-height : 0px);
    animate height { duration: dur; easing: ease-out; }

    VerticalLayout {
        Rectangle {height: 10px;}
        touch-area:=TouchArea {
            
            clicked => {
                debug("hit");
                if (root.enabled) {
                    root.checked = !root.checked;
                    root.toggled();
                }
            }
            state-layer := StateLayer {
                width: 100%;
                height: 100%;
                has-hover: touch-area.has-hover;
                pressed: touch-area.pressed;
            }

            header := Rectangle {
                width: 100%;
                height: 60px;
                background: headerBG;
            }


            HorizontalLayout {
                width: 100%;
                x:10px;
                accordionIcon:=Image {
                    source:Icons.add;
                    colorize: Palette.foreground;
                    horizontal-stretch: 0;
                    horizontal-alignment: right;
                    vertical-alignment: center;
                    width:20px;
                    rotation-angle: root.checked ? 180deg : 0deg ;
                    animate rotation-angle {duration: dur/2; easing: ease-in;
                         
                    }
                }
                Rectangle {width: 10px;}
                // Text {
                //     text: root.checked ? "↓" : "→";
                //     width: 30px;
                //     font-size: 20px;
                //     vertical-alignment: center;
                // }
                Text {
                    text: root.title;
                    horizontal-stretch: 1;
                    font-size: EditorFontSettings.body.font-size;
                    font-weight: EditorFontSettings.body.font-weight;
                    vertical-alignment: center;
                }
            }
        }
        content := Rectangle {
            width: 100%;
            background: headerBG;
            // visible: root.checked ? false : true;
            height: root.checked ? self.preferred-height : 0px;
            animate height { 
                duration: dur;
                easing: ease-out;
            }
            VerticalLayout {
                @children
                spacing: -5pt;
            }  
        }
            // Rectangle {height:40px;}
    }
}
component ExpandableGroup {
    in property <ElementInformation> element-information;
    in property <string> text;
    in property <[PropertyInformation]> properties;

    property <bool> open: true;
    Rectangle {
        background: Palette.alternate-background;

        content-layer := VerticalLayout {
            // header
            Rectangle {
                touch-area := TouchArea {
                    clicked => {
                        root.open = !root.open;
                    }
                }

                state-layer := StateLayer {
                    width: 100%;
                    height: 100%;
                    has-hover: touch-area.has-hover;
                    pressed: touch-area.pressed;
                }

                HorizontalBox {
                    icon-image := Image {
                        width: EditorSizeSettings.default-icon-width;
                        colorize: Palette.foreground;
                        source: Icons.drop-down;
                        rotation-origin-x: self.width / 2;
                        rotation-origin-y: self.height / 2;
                        states [
                            closed when !root.open: {
                                rotation-angle: -0.25turn;
                            }
                        ]

                        animate rotation-angle { duration: EditorAnimationSettings.roation-duration; }
                    }

                    BodyStrongText {
                        text: root.text;
                    }
                }
            }

            if root.open: VerticalBox {
                for property in root.properties: HorizontalLayout {
                    spacing: parent.spacing;

                    if property.value.kind == PropertyValueKind.string: HorizontalLayout {
                        LengthProperty {
                            property-name: property.name;
                        }

                        /*
                        edited(text) => {
                            // overlay.visible = !Api.test-string-binding(
                            //     root.element-information.source-uri,
                            //     root.element-information.source-version,
                            //     root.element-information.range.start,
                            //     property.name,
                            //     text,
                            //     property.value.is-translatable,
                            //     property.value.tr-context,
                            //     property.value.tr-plural,
                            //     property.value.tr-plural-expression,
                            // );
                        }

                        accepted(text) => {
                            Api.set-string-binding(
                                root.element-information.source-uri,
                                root.element-information.source-version,
                                root.element-information.range.start,
                                property.name,
                                text,
                                property.value.is-translatable,
                                property.value.tr-context,
                                property.value.tr-plural,
                                property.value.tr-plural-expression,
                            );
                        }
                    */
                    }
                    if (property.value.kind == PropertyValueKind.color || property.value.kind == PropertyValueKind.brush): ExpandableProperty {
                        title:  property.name;
                        ColourWidget { }
                    }
                    if property.value.kind == PropertyValueKind.code: HorizontalLayout {
                        BodyText {
                            min-width: EditorSizeSettings.min-prefix-text-width;
                            text: property.name;
                        }

                        ResetButton {
                            element-information <=> root.element-information;
                            property-information: property;
                        }

                        CodeButton {
                            element-information <=> root.element-information;
                            property-information: property;
                        }
                    }
                }
            }
        }
    }
}

export component PropertyView {
    in property <ElementInformation> current-element <=> Api.current-element;
    in property <[PropertyGroup]> properties <=> Api.properties;

    property <length> key-width: self.width / 2.5;
    property <bool> element-loaded: root.properties.length > 0;

    width: EditorSizeSettings.property-bar-width;

    // background-layer := Rectangle {
    //     background: Palette.alternate-background;
    // }

    content-layer := VerticalLayout {
        // padding: background-layer.border-width;

        GroupHeader {
            title: @tr("{} Properties", root.current-element.type-name);
            vertical-stretch: 0;
        }

        if !root.element-loaded: Text {
            text: @tr("Select an Element");
            horizontal-alignment: center;
            vertical-alignment: center;
            vertical-stretch: 1;
        }

        if root.element-loaded: ScrollView {
            VerticalBox {
                alignment: start;

                for group in root.properties : ExpandableGroup {
                    text: group.group-name;

                    element-information <=> root.current-element;
                    properties: group.properties;
                }
            }

            // VerticalLayout {
            //     if root.current-element.properties.length > 0: Rectangle {
            //         VerticalLayout {
            //             alignment: start;

            //             header := TypeHeader {
            //                 type-name: root.current-element.type-name;
            //                 id: root.current-element.id;
            //             }

            //             for group in root.current-element.properties: Rectangle {
            //                 VerticalBox {
            //                     if group.group-name != "" && group.group-name != root.current-element.type-name: BodyText {
            //                         text: group.group-name;
            //                     }

            //                     for property in group.properties: property-row := HorizontalLayout {
            //                         private property <string> property-name: property.name;
            //                         private property <string> property-type: property.type-name;
            //                         private property <PropertyValue> property-value: property.value;

            //                         private property <bool> is-defined: self.property-value.code != "";

            //                         private property <brush> text-foreground: property-row.is-defined ? Palette.foreground : Palette.foreground.transparentize(0.5);

            //                         spacing: 4px;
            //                         alignment: stretch;

            //                         TouchArea {
            //                             width: root.key-width;
            //                             horizontal-stretch: 0;

            //                             key := Text {
            //                                 width: 100%;
            //                                 color: property-row.text-foreground;
            //                                 vertical-alignment: center;
            //                                 text: property.name;
            //                             }

            //                             clicked() => {
            //                                 Api.show-document-offset-range(root.current-element.source-uri, property.defined-at.expression-range.start, property.defined-at.expression-range.start);
            //                             }
            //                         }

            //                         Rectangle {
            //                             min-height: 20px;
            //                             horizontal-stretch: 1;

            //                             private property <bool> have-simple-ui: false;

            //                             if property-row.property-value.kind == PropertyValueKind.code && property-row.property-value.code != "": Button {
            //                                 text: @tr("Code");
            //                                 clicked() => {
            //                                     Api.show-document-offset-range(root.current-element.source-uri, property.defined-at.expression-range.start, property.defined-at.expression-range.start);
            //                                 }
            //                             }
            //                             if property-row.property-value.kind == PropertyValueKind.code && property-row.property-value.code == "": Text {
            //                                 text: @tr("<unset>");
            //                             }
            //                             if property-row.property-value.kind == PropertyValueKind.boolean: CheckBox {
            //                                 x: 0;
            //                                 checked: property-row.property-value.value_bool;

            //                                 toggled() => {
            //                                     Api.set-code-binding(
            //                                         root.current-element.source-uri,
            //                                         root.current-element.source-version,
            //                                         root.current-element.range.start,
            //                                         property.name,
            //                                         self.checked ? "true" : "false",
            //                                     );
            //                                 }
            //                             }
            //                             if property-row.property-value.kind == PropertyValueKind.string: LineEdit {
            //                                 width: 100%;
            //                                 // otherwise this gets too high and covers several rows.
            //                                 height: 100%;
            //                                 text: property-row.property-value.value-string;

            //                                 edited(text) => {
            //                                     overlay.visible = !Api.test-string-binding(
            //                                         root.current-element.source-uri,
            //                                         root.current-element.source-version,
            //                                         root.current-element.range.start,
            //                                         property.name,
            //                                         text,
            //                                         property-row.property-value.is-translatable,
            //                                         property-row.property-value.tr-context,
            //                                         property-row.property-value.tr-plural,
            //                                         property-row.property-value.tr-plural-expression,
            //                                     );
            //                                 }

            //                                 accepted(text) => {
            //                                     Api.set-string-binding(
            //                                         root.current-element.source-uri,
            //                                         root.current-element.source-version,
            //                                         root.current-element.range.start,
            //                                         property.name,
            //                                         text,
            //                                         property-row.property-value.is-translatable,
            //                                         property-row.property-value.tr-context,
            //                                         property-row.property-value.tr-plural,
            //                                         property-row.property-value.tr-plural-expression,
            //                                     );
            //                                 }
            //                             }
            //                             if property-row.property-value.kind == PropertyValueKind.enum: ComboBox {
            //                                 width: 100%;
            //                                 // otherwise this gets too high and covers several rows.
            //                                 height: 100%;

            //                                 current-index: property-row.property-value.value-int;

            //                                 model: property-row.property-value.visual-items;

            //                                 selected(value) => {
            //                                     Api.set-code-binding(
            //                                         root.current-element.source-uri,
            //                                         root.current-element.source-version,
            //                                         root.current-element.range.start,
            //                                         property.name,
            //                                         property-value.value_string + "." + value,
            //                                     )
            //                                 }
            //                             }

            //                             overlay := Rectangle {
            //                                 visible: false;
            //                                 background: #80000040;

            //                                 width: parent.width - 8px;
            //                                 height: parent.height - 8px;
            //                                 border-radius: 3px;
            //                             }
            //                         }
            //                     }
            //                 }
            //             }
            //         }
            //    }

           //}
        }
    }

    Rectangle {
        x: 0;
        width: 1px;
        background: Palette.border;
    }
}
