// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { LineEdit, Palette, VerticalBox, CheckBox, ComboBox, ScrollView, Button, HorizontalBox, SpinBox, Slider } from "std-widgets.slint";

import { Api, ElementInformation, PropertyDeclaration, PropertyGroup, PropertyInformation, PropertyValue, PropertyValueKind } from "../api.slint";
import { GroupHeader } from "../components/group.slint";
import { BodyStrongText } from "../components/body-strong-text.slint";
import { BodyText } from "../components/body-text.slint";
import { StateLayer } from "../components/state-layer.slint";
import { EditorSizeSettings, Icons, EditorAnimationSettings, EditorSpaceSettings, EditorSizeSettings, EditorFontSettings, EditorPalette } from "../components/styling.slint";

export global style {
    out property <length> grid-margin:5px;
    out property <length> min-distance:5px;
}

component CodeButton inherits Button {
    in property <ElementInformation> element-information;
    in property <PropertyInformation> property-information;

    text: @tr("Code");
    clicked => {
        Api.show-document-offset-range(
            element-information.source-uri,
            Api.property-declaration-ranges(property-information.name).defined-at.expression-range.start,
            Api.property-declaration-ranges(property-information.name).defined-at.expression-range.start,
            true,
        );
    }
}

component ResetButton inherits Button {
    in property <ElementInformation> element-information;
    in property <PropertyInformation> property-information;

    text: @tr("Reset");
    clicked => {
        Api.set-code-binding(
            element-information.source-uri,
            element-information.source-version,
            element-information.range.start,
            property-information.name,
            "",
        );
    }
}

component NameLabel inherits HorizontalLayout {
    in property <string> property-name;

    horizontal-stretch: 0;

    Rectangle {
        width: EditorSpaceSettings.group-indent;
    }

    BodyText {
        min-width: EditorSizeSettings.min-prefix-text-width;
        text: root.property-name;
        font-size: 1rem;
        overflow: elide;
    }
}

component FloatWidget inherits HorizontalLayout {
    in property <ElementInformation> element-information;
    in property <PropertyInformation> property-information;

    private property <string> current-unit;
    spacing: EditorSpaceSettings.default-spacing;
    padding-top: EditorSpaceSettings.property-spacing;
    alignment: space-between;
    width: 100%;

    NameLabel {
        property-name: property-information.name;
    }

    HorizontalLayout {
        alignment: end;
        number := LineEdit {
            horizontal-alignment: right;
            text: property-information.value.value-float;
            min-width: EditorSizeSettings.float-size;
            max-width: 14rem;
            horizontal-stretch: 0;
            font-size: 1rem;

            accepted(text) => {
                Api.set-code-binding(
                    root.element-information.source-uri,
                    root.element-information.source-version,
                    root.element-information.range.start,
                    root.property-information.name,
                    number.text + root.current-unit,
                );
            }
        }

        if property-information.value.visual-items.length > 1: ComboBox {
            min-width: EditorSizeSettings.length-combo;
            model: property-information.value.visual-items;
            current-index: property-information.value.code == "" ? property-information.value.default-selection : property-information.value.value-int;

            changed current-index => {
                root.current-unit = self.model[self.current-index];
            }

            horizontal-stretch: 0;

            selected(unit) => {
                Api.set-code-binding(
                    root.element-information.source-uri,
                    root.element-information.source-version,
                    root.element-information.range.start,
                    root.property-information.name,
                    number.text + root.current-unit,
                );
            }
        }
        if property-information.value.visual-items.length == 1: Text {
            text: property-information.value.visual-items[0];

            changed text => {
                root.current-unit = self.text;
            }
        }
    }
}

component ImageWidget {
    in property <ElementInformation> element-information;
    in property <PropertyInformation> property-information;

    HorizontalLayout {
        spacing: EditorSpaceSettings.default-spacing;

        BodyText {
            text: "source:";
            horizontal-stretch: 0;
        }

        Rectangle {
            width: EditorSpaceSettings.default-padding;
            horizontal-stretch: 1;
        }

        // alignment: stretch;
        Button {
            text: "Browse...";
        }

        Rectangle {
            border-color: Palette.border;
            width: 50px;
            height: 50px;
            Image { }
        }
    }
}

component ColorWidget inherits Rectangle {
    in property <ElementInformation> element-information;
    in property <PropertyInformation> property-information;

    property <int> gVal:30;
    in property <string> title:"Colour";
    background: Palette.alternate-background;
    VerticalLayout {
        spacing: EditorSpaceSettings.default-spacing;
        HorizontalLayout {
            padding-top: EditorSpaceSettings.property-spacing;
            alignment: stretch;
            BodyText {
                text: title;
                font-size: 1rem;
                horizontal-stretch: 0;
            }

            Rectangle {
                width: EditorSpaceSettings.default-spacing;
                horizontal-stretch: 1;
            }

            // alignment: stretch;
            Rectangle {
                background: red;
                width: EditorSizeSettings.default-icon-width;
                horizontal-stretch: 0;
            }

            hex := LineEdit {
                text: "#ff0000";
                horizontal-stretch: 0;
                min-width: EditorSizeSettings.hex-size;
            }
        }

        HorizontalLayout {
            padding-top: EditorSpaceSettings.property-spacing;
            spacing: EditorSpaceSettings.default-spacing;
            alignment: stretch;
            ComboBox {
                model: ["RGB", "RGBA", "HSL", "Palettes"];
                horizontal-stretch: 1;
            }
        }

        HorizontalLayout {
            padding-top: EditorSpaceSettings.property-spacing;
            spacing: EditorSpaceSettings.default-spacing;
            alignment: stretch;
            Text {
                text: "r:";
                horizontal-stretch: 0;
                vertical-alignment: center;
            }

            // Slider {
            //     visible: (parent.width > 200px);
            //     value: 255;
            // }

            LineEdit {
                input-type: number;
                horizontal-stretch: 1;
                text: 255;
                min-width: 10rem;
            }
        }

        HorizontalLayout {
            spacing: EditorSpaceSettings.default-spacing;
            padding-top: EditorSpaceSettings.property-spacing;

            alignment: stretch;
            Text {
                text: "g:";
                horizontal-stretch: 0;
                vertical-alignment: center;
            }

            /*
            Rectangle {
                visible: (root.width > 200px);
                Slider {
                    z: 1;
                    x: 0;
                    value: gVal;
                }

                Rectangle {
                    width: gVal * 1px;
                    height: 3px;
                    background: green;
                    x: 0;
                    y: 0;
                }
            }
            */

            LineEdit {
                input-type: number;
                horizontal-stretch: 1;
                text: gVal;
                min-width: 10rem;
            }
        }

        HorizontalLayout {
            spacing: EditorSpaceSettings.default-spacing;
            padding-top: EditorSpaceSettings.property-spacing;
            alignment: stretch;
            Text {
                text: "b:";
                horizontal-stretch: 0;
                vertical-alignment: center;
            }

            // Slider {
            //     visible: (parent.width > 200px);
            //     value: 0;
            // }

            LineEdit {
                input-type: number;
                horizontal-stretch: 1;
                min-width: 10rem;
                text: 0;
            }
        }
    }
}

export component ExpandableProperty inherits Rectangle {
    callback toggled;
    in-out property <bool> checked:false;
    property <duration> dur:300ms;
    in-out property <color> headerBG: Palette.alternate-background;
    in-out property <bool> enabled:true;
    in property <string> title: "Title";
    clip: true;
    height: header.height + EditorSpaceSettings.default-spacing + (root.checked ? content.preferred-height : 0px);
    animate height {
        duration: dur;
        easing: ease-out;
    }

    VerticalLayout {
        x:0;
        spacing: EditorSpaceSettings.default-spacing;
        Rectangle {
            height: 5px;
        }
        touch-area := TouchArea {
            clicked => {
                debug("hit");
                if (root.enabled) {
                    root.checked = !root.checked;
                    root.toggled();
                }
            }
            state-layer := StateLayer {
                width: 100%;
                height: 100%;
                has-hover: touch-area.has-hover;
                pressed: touch-area.pressed;
            }

            header := Rectangle {
                width: 100%;
                height: 30px;
                background: headerBG;
            }

            HorizontalLayout {
                x: 0;
                y: 0;
                width: 100%;
                alignment: stretch;

                accordionIcon := Image {
                    width: EditorSpaceSettings.group-indent;
                    source: Icons.add;
                    colorize: Palette.foreground;
                    vertical-alignment: top;
                    visible: state-layer.has-hover;
                    rotation-angle: root.checked ? 180deg : 0deg;
                    animate rotation-angle {
                        duration: dur / 2;
                        easing: ease-in;
                    }
                }

                content := Rectangle {
                    background: headerBG;
                    // visible: root.checked ? false : true;
                    height: root.checked ? self.preferred-height : 10px;
                    animate height {
                        duration: dur;
                        easing: ease-out;
                    }
                    VerticalLayout {
                        width: 100%;
                        @children
                    }
                }
            }
        }

        // Rectangle {height:40px;}
    }
}

component ExpandableGroup {
    in property <ElementInformation> element-information;
    in property <string> text;
    in property <[PropertyInformation]> properties;

    property <bool> open: true;
    Rectangle {
        background: Palette.alternate-background;

        content-layer := VerticalLayout {
            // header
            spacing: EditorSpaceSettings.default-spacing;

            if text != "": Rectangle {
                touch-area := TouchArea {
                    clicked => {
                        root.open = !root.open;
                    }
                }

                state-layer := StateLayer {
                    width: 100%;
                    height: 100%;
                    has-hover: touch-area.has-hover;
                    pressed: touch-area.pressed;
                }

                HorizontalLayout {
                    icon-image := Image {
                        width: EditorSizeSettings.default-icon-width;
                        colorize: Palette.foreground;
                        source: Icons.drop-down;
                        rotation-origin-x: self.width / 2;
                        rotation-origin-y: self.height / 2;
                        states [
                            closed when !root.open: {
                                rotation-angle: -0.25turn;
                            }
                        ]

                        animate rotation-angle { duration: EditorAnimationSettings.roation-duration; }
                    }

                    BodyStrongText {
                        text: root.text;
                    }
                }
            }

            if root.open: VerticalLayout {
                spacing: EditorSpaceSettings.property-spacing;
                for property in root.properties: HorizontalLayout {
                    alignment: stretch;

                    if property.value.kind == PropertyValueKind.boolean: HorizontalLayout {
                        spacing: EditorSpaceSettings.default-spacing;

                        NameLabel {
                            property-name: property.name;
                        }

                        CheckBox {
                            checked: property.value.value_bool;

                            toggled() => {
                                Api.set-code-binding(
                                    root.element-information.source-uri,
                                    root.element-information.source-version,
                                    root.element-information.range.start,
                                    property.name,
                                    self.checked ? "true" : "false",
                                );
                            }
                        }
                    }
                    if (property.value.kind == PropertyValueKind.color) || (property.value.kind == PropertyValueKind.brush): ColorWidget {
                        element-information <=> root.element-information;
                        property-information: property;
                    }
                    if property.value.kind == PropertyValueKind.code: HorizontalLayout {
                        spacing: EditorSpaceSettings.default-spacing;
                        alignment: space-between;
                        padding-top: 2px;

                        NameLabel {
                            property-name: property.name;
                        }

                        if property.value.code == "": HorizontalLayout {
                            Text {
                                text: @tr("unset");
                            }
                        }
                        if property.value.code != "": HorizontalLayout {
                            ResetButton {
                                element-information <=> root.element-information;
                                property-information: property;
                            }

                            CodeButton {
                                element-information <=> root.element-information;
                                property-information: property;
                            }
                        }
                    }
                    if property.value.kind == PropertyValueKind.enum: HorizontalLayout {
                        spacing: EditorSpaceSettings.default-spacing;

                        NameLabel {
                            property-name: property.name;
                        }

                        HorizontalLayout {
                            ComboBox {
                                current-index: property.value.value-int;

                                model: property.value.visual-items;

                                selected(value) => {
                                    Api.set-code-binding(
                                        root.element-information.source-uri,
                                        root.element-information.source-version,
                                        root.element-information.range.start,
                                        property.name,
                                        property.value.value_string + "." + value,
                                    )
                                }
                            }
                        }
                    }
                    if property.value.kind == PropertyValueKind.float:  FloatWidget {
                        element-information <=> root.element-information;
                        property-information: property;
                    }
                    if property.value.kind == PropertyValueKind.image: ImageWidget {
                        element-information <=> root.element-information;
                        property-information: property;
                    }
                    if property.value.kind == PropertyValueKind.integer: HorizontalLayout {
                        spacing: EditorSpaceSettings.default-spacing;

                        NameLabel {
                            property-name: property.name;
                        }

                        LineEdit {
                            input-type: number;
                            text: property.value.value-int;

                            accepted(text) => {
                                Api.set-code-binding(
                                    root.element-information.source-uri,
                                    root.element-information.source-version,
                                    root.element-information.range.start,
                                    property.name,
                                    text,
                                );
                            }
                        }
                    }
                    if property.value.kind == PropertyValueKind.string: HorizontalLayout {
                        spacing: EditorSpaceSettings.default-spacing;

                        NameLabel {
                            property-name: property.name;
                        }

                        LineEdit {
                            text: property.value.value-string;
                            accepted(text) => {
                                Api.set-string-binding(
                                    root.element-information.source-uri,
                                    root.element-information.source-version,
                                    root.element-information.range.start,
                                    property.name,
                                    text,
                                    property.value.is-translatable,
                                    property.value.tr-context,
                                    property.value.tr-plural,
                                    property.value.tr-plural-expression,
                                );
                            }
                        }
                    }
                }
            }
        }
    }
}

export component PropertyView {
    in property <ElementInformation> current-element <=> Api.current-element;
    in property <[PropertyGroup]> properties <=> Api.properties;

    property <length> key-width: self.width / 2.5;
    property <bool> element-loaded: root.properties.length > 0;

    width: EditorSizeSettings.property-bar-width;

    content-layer := VerticalLayout {
        GroupHeader {
            title: @tr("{} Properties", root.current-element.type-name);
            vertical-stretch: 0;
        }

        if !root.element-loaded: Text {
            text: @tr("Select an Element");
            horizontal-alignment: center;
            vertical-alignment: center;
            vertical-stretch: 1;
        }

        if root.element-loaded: ScrollView {
            VerticalBox {
                alignment: start;

                for group in root.properties: ExpandableGroup {
                    text: group.group-name;

                    element-information <=> root.current-element;
                    properties: group.properties;
                }
            }
        }
    }

    Rectangle {
        x: 0;
        width: 1px;
        background: Palette.border;
    }
}
